# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CriarSU.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(557, 277)
        MainWindow.setMinimumSize(QtCore.QSize(557, 277))
        MainWindow.setMaximumSize(QtCore.QSize(557, 277))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QLineEdit {\n"
"background-color: rgb(55, 55, 64);\n"
"border-radius: 3px;\n"
"color: rgb(202, 202, 202);\n"
"}\n"
"QLineEdit:hover {\n"
"border:2px solid rgb(255, 242, 79);\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgba(45, 47, 67, 0.8);\n"
"border-radius: 10px;\n"
"color: rgb(202, 202, 202);\n"
"font: 11pt \"Segoe MDL2 Assets\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(45, 47, 67);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.inputUser = QtWidgets.QLineEdit(self.frame)
        self.inputUser.setMinimumSize(QtCore.QSize(100, 40))
        self.inputUser.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputUser.setFont(font)
        self.inputUser.setText("")
        self.inputUser.setAlignment(QtCore.Qt.AlignCenter)
        self.inputUser.setObjectName("inputUser")
        self.gridLayout_2.addWidget(self.inputUser, 1, 0, 1, 1)
        self.btnCriar = QtWidgets.QPushButton(self.frame)
        self.btnCriar.setMinimumSize(QtCore.QSize(100, 40))
        self.btnCriar.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnCriar.setFont(font)
        self.btnCriar.setObjectName("btnCriar")
        self.gridLayout_2.addWidget(self.btnCriar, 1, 1, 2, 1)
        self.checkAdm = QtWidgets.QCheckBox(self.frame)
        self.checkAdm.setObjectName("checkAdm")
        self.gridLayout_2.addWidget(self.checkAdm, 3, 0, 1, 1)
        self.inputPass = QtWidgets.QLineEdit(self.frame)
        self.inputPass.setMinimumSize(QtCore.QSize(0, 40))
        self.inputPass.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputPass.setFont(font)
        self.inputPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPass.setAlignment(QtCore.Qt.AlignCenter)
        self.inputPass.setObjectName("inputPass")
        self.gridLayout_2.addWidget(self.inputPass, 2, 0, 1, 1)
        self.labelCheck = QtWidgets.QLabel(self.frame)
        self.labelCheck.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCheck.setFont(font)
        self.labelCheck.setText("")
        self.labelCheck.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCheck.setObjectName("labelCheck")
        self.gridLayout_2.addWidget(self.labelCheck, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Criar Super User"))
        self.inputUser.setPlaceholderText(_translate("MainWindow", "USER"))
        self.btnCriar.setText(_translate("MainWindow", "Criar"))
        self.checkAdm.setText(_translate("MainWindow", "Administrador"))
        self.inputPass.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
