# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(383, 200)
        Dialog.setMinimumSize(QtCore.QSize(285, 140))
        Dialog.setMaximumSize(QtCore.QSize(5211, 5151))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("QLineEdit {\n"
"background-color: rgb(55, 55, 64);\n"
"border-radius: 3px;\n"
"color: rgb(202, 202, 202);\n"
"}\n"
"QLineEdit:hover {\n"
"border:2px solid rgb(255, 242, 79);\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgba(45, 47, 67, 0.8);\n"
"border-radius: 10px;\n"
"color: rgb(202, 202, 202);\n"
"font: 11pt \"Segoe MDL2 Assets\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(45, 47, 67);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.inputImprimirLogin = QtWidgets.QLineEdit(self.frame)
        self.inputImprimirLogin.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputImprimirLogin.setFont(font)
        self.inputImprimirLogin.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImprimirLogin.setObjectName("inputImprimirLogin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputImprimirLogin)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.inputImprimirSenha = QtWidgets.QLineEdit(self.frame)
        self.inputImprimirSenha.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputImprimirSenha.setFont(font)
        self.inputImprimirSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputImprimirSenha.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImprimirSenha.setObjectName("inputImprimirSenha")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inputImprimirSenha)
        self.btnImprimirLogar = QtWidgets.QPushButton(self.frame)
        self.btnImprimirLogar.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnImprimirLogar.setFont(font)
        self.btnImprimirLogar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnImprimirLogar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnImprimirLogar.setObjectName("btnImprimirLogar")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnImprimirLogar)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.labelCheck = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCheck.setFont(font)
        self.labelCheck.setText("")
        self.labelCheck.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCheck.setObjectName("labelCheck")
        self.gridLayout.addWidget(self.labelCheck, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Logar para imprimir"))
        self.label.setText(_translate("Dialog", "Login"))
        self.inputImprimirLogin.setPlaceholderText(_translate("Dialog", "USER"))
        self.label_2.setText(_translate("Dialog", "Senha"))
        self.inputImprimirSenha.setPlaceholderText(_translate("Dialog", "PASSWORD"))
        self.btnImprimirLogar.setText(_translate("Dialog", "Logar"))
